M48
; DRILL file {KiCad 9.0.3} date 2025-09-02T15:34:36-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-02T15:34:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X70.675Y-24.161
T1
G00X63.625Y-24.161
M15
G01X63.325Y-24.161
M16
G05
M30
